language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

services:
  - memcached
  - redis-server

before_script:
  - composer update
  - phpenv config-add build/travis/phpenv/memcached.ini
  - phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini
  - phpenv config-add build/travis/phpenv/redis.ini

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs -p --report=full --extensions=php --standard=.travis/phpcs/Joomla/ruleset.xml src/
