language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached
  - redis-server

before_script:
  - composer update --dev
  - phpenv config-add build/travis/phpenv/memcached.ini
  - phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini
  - phpenv config-add build/travis/phpenv/redis.ini

script:
  - phpunit
